name: 'Setup build scan'
description: 'Sets up build scan support in your GitHub Actions workflow.'
author: 'Benjamin Muschko'
inputs:
  gradle-enterprise-plugin-version:
    description: Gradle enterprise plugin version that provides build scan functionality.
    default: '3.16.1'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'activity'
  color: 'blue'