name: 'Setup build scan'
description: 'Sets up Gradle build scan support in your GitHub Actions workflow.'
author: 'Benjamin Muschko'
inputs:
  develocity-gradle-plugin-version:
    description: Develocity Gradle plugin version that provides build scan functionality.
    default: '3.16.2'
    required: true
  common-user-data-plugin-version:
    description: Gradle plugin version that provides common user data with build scan.
    default: '1.12.1'
    required: true
  tags:
    description: Tags to send with build scan.
    required: false
  links:
    description: Links to send with build scan.
    required: false
outputs:
  init-script-path:
    description: The path to the init script that sets up the build scan functionality.
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'activity'
  color: 'blue'