name: Integration Test
on: [push, pull_request]

jobs:
  integration-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: npm
    - name: Build distribution
      shell: bash
      run: |
        npm install
        npm run build
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set up build scan
      id: setup-build-scan
      uses: ./
      with:
        support-maven: true
    - name: Execute Maven build
      working-directory: .github/sample-builds/maven-build
      run: mvn verify