name: Integration Test Gradle
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  integration-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: npm
    - name: Build distribution
      shell: bash
      run: |
        npm install
        npm run build
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: current
    - name: Set up build scan
      id: setup-build-scan
      uses: ./
      with:
        tags: 'integ-test,${{ matrix.os }}'
        links: 'Developer=https://github.com/bmuschko'
    - name: Execute Gradle build
      id: gradle
      working-directory: .github/sample-builds/gradle-build
      run: gradle test
    - name: Check build scan URL
      if: ${{ !steps.gradle.outputs.build-scan-url }}
      uses: actions/github-script@v7
      with:
        script: |
          core.setFailed('No build scan detected')   